// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowEngine.Tests.UI.Backend.Data;

#nullable disable

namespace WorkflowEngine.Tests.UI.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210000000_AddMessageOptions")]
    partial class AddMessageOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.ConversationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActiveLeafMessageId")
                        .HasColumnType("text")
                        .HasColumnName("active_leaf_message_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastCheckpointId")
                        .HasColumnType("text")
                        .HasColumnName("last_checkpoint_id");

                    b.Property<string>("LastInterruptRequestId")
                        .HasColumnType("text")
                        .HasColumnName("last_interrupt_request_id");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text")
                        .HasColumnName("thread_id");

                    b.Property<string>("WorkflowType")
                        .HasColumnType("text")
                        .HasColumnName("workflow_type");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActiveLeafMessageId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CheckpointId")
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_id");

                    b.Property<string>("CheckpointNs")
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_ns");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ParentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ConversationId", "ParentId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.ConversationEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageEntity", "ActiveLeafMessage")
                        .WithMany()
                        .HasForeignKey("ActiveLeafMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveLeafMessage");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Tests.UI.Backend.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Conversation");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.ConversationEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
