// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowEngine.Tests.UI.Backend.Data;

#nullable disable

namespace WorkflowEngine.Tests.UI.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128212310_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.DialogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActiveRootVersionId")
                        .HasColumnType("text")
                        .HasColumnName("active_root_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastCheckpointId")
                        .HasColumnType("text")
                        .HasColumnName("last_checkpoint_id");

                    b.Property<string>("LastInterruptRequestId")
                        .HasColumnType("text")
                        .HasColumnName("last_interrupt_request_id");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thread_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_type");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRootVersionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ThreadId");

                    b.ToTable("dialogs");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageVersionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CheckpointId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("DialogId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dialog_id");

                    b.Property<string>("ParentVersionId")
                        .HasColumnType("text")
                        .HasColumnName("parent_version_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("DialogId");

                    b.HasIndex("ParentVersionId");

                    b.HasIndex("Path");

                    b.HasIndex("DialogId", "Depth");

                    b.HasIndex("DialogId", "Path");

                    b.ToTable("message_versions");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.DialogEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageVersionEntity", "ActiveRootVersion")
                        .WithMany()
                        .HasForeignKey("ActiveRootVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveRootVersion");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageVersionEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Tests.UI.Backend.Data.Entities.DialogEntity", "Dialog")
                        .WithMany("Versions")
                        .HasForeignKey("DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageVersionEntity", "ParentVersion")
                        .WithMany("ChildVersions")
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dialog");

                    b.Navigation("ParentVersion");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.DialogEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WorkflowEngine.Tests.UI.Backend.Data.Entities.MessageVersionEntity", b =>
                {
                    b.Navigation("ChildVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
